### PR TITLE
Add resource-class to node/lease

### PR DESCRIPTION
**Pull request by DanNiESh**
Functional tests succeeded.

### CODE REVIEW

**Review by tzumainn — CHANGES_REQUESTED** [review]
Looks good! I think the one thing missing is that the resource class should be displayed when listing leases/offers.

**Comment by tzumainn** [comment]
> > Looks good! I think the one thing missing is that the resource class should be displayed when listing leases/offers.
> 
> It's displayed when we add "--long" in the commands. Do we want to add it to short list?

Yep!

**Comment by DanNiESh** [comment]
> > > Looks good! I think the one thing missing is that the resource class should be displayed when listing leases/offers.
> > 
> > 
> > It's displayed when we add "--long" in the commands. Do we want to add it to short list?
> 
> Yep!

Fixed. Also tested in demo server. Now we can see "resource class" when listing offers/leases.

**Comment by tzumainn** [comment]
Thanks! One last request - can you change the order of fields so it goes "resource | resource_class", instead of resource_class being at the end?

**Comment by DanNiESh** [comment]
> Thanks! One last request -

Sure!

**Comment by DanNiESh** [comment]
> > Thanks! One last request -
> 
> Sure!

Fixed.

**Review by tzumainn — APPROVED** [review]

**Comment by tzumainn** [comment]
Looks great - thanks!

**Pull request merged**
