### PR TITLE
Update ESI CLI to return properties as dictionaries in lease,offer and node list

### PR DESCRIPTION
**Pull request by skanthed**

### CODE REVIEW

**Review by tzumainn — CHANGES_REQUESTED** [review]
Looks good! One request - I think there's probably a `formatted_node_properties` variable in `fakes.py` that can be removed - can you get rid of it?

**Comment by skanthed** [comment]
@tzumainn -- 
Do we need to update the` lease_show` and `offer_show` functions as well? They currently return strings and utilize `formatted_node_properties`

https://github.com/CCI-MOC/python-esileapclient/blob/56b3da5d90aa0b3ea6b57a1b7e33be1b9b7b2de7/esileapclient/tests/unit/osc/v1/test_lease.py#L304

**Comment by tzumainn** [comment]
Ah, yes - good catch!

**Comment by skanthed** [comment]
@tzumainn I will update the PR.

**Review by tzumainn — APPROVED** [review]

**Comment by tzumainn** [comment]
Looks good - thanks!

**Pull request merged**
